# Generated by Django 3.1.7 on 2021-03-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_auto_20210312_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
